package com.search.sdasearch.dao;

import com.search.sdasearch.entity.*;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import java.util.*;

/**************************************/
/*                                    */
/*  Program: SDA-Search               */
/*  Author: Paul Trudel               */
/*                                    */
/*  Class for handling the database   */
/*  interaction for the SDADocument   */
/*  entity                            */
/*                                    */
/**************************************/

public class SDADocumentDAO {

    private SessionFactory sessionFactory; // Hibernate SessionFactory
    private Logger logger = LoggerFactory.getLogger(SDADocumentDAO.class);
    private static SDADocumentDAO instance;

    private SDADocumentDAO() {
        openConnection();
    }

    public static SDADocumentDAO getInstance() {
        if(instance == null) {
            instance = new SDADocumentDAO();
        }
        return instance;
    }

    // Initialize connection to the database
    private void openConnection() {
        logger.info("Opening connection to database");
        sessionFactory = new Configuration()
                .configure("hibernate.cfg.xml")
                .addAnnotatedClass(SDADocument.class)
                .addAnnotatedClass(DocumentHeading.class)
                .addAnnotatedClass(DocumentImage.class)
                .addAnnotatedClass(DocumentLink.class)
                .addAnnotatedClass(DocumentMetadata.class)
                .addAnnotatedClass(DocumentParagraph.class)
                .buildSessionFactory();
    }

    // Persist the given SDADocument to the database
    public Long save(SDADocument sdaDocument) {
        logger.info("Saving document {}", sdaDocument.getUrl());
        Long docId = null;
        Session session = sessionFactory.openSession(); // Open a new Hibernate sessions
        Transaction transaction = null;

        try {
            transaction = session.beginTransaction(); // Begin the transaction
            docId = (Long) session.save(sdaDocument); // Save the SDADocument entity
            transaction.commit(); // Commit the transactions
        } catch (Exception e) {
            if (transaction != null) {
                transaction.rollback();
                e.printStackTrace();
            }
        } finally {
            session.close(); // Close the session
        }
        return docId; // Return the ID generated by the database
    }

    // Find an SDADocument entity corresponding to the given ID
    public SDADocument find(Long id) {
        Session session = sessionFactory.openSession(); // Open a new Hibernate session
        Transaction transaction = null;
        SDADocument result = null;

        try {
            transaction = session.beginTransaction(); // Begin the transaction
            result = session.find(SDADocument.class, id); // Retrieve the entity from the database
            transaction.commit(); // Commit the transaction
        } catch (Exception e) {
            if(transaction != null) {
                transaction.rollback();
                e.printStackTrace();
            }
        } finally {
            session.close(); // Close the session
        }
        return result; // Return the result
    }

    // Find an SDADocument entity corresponding the given URL
    public SDADocument findDocumentByUrl(String url) {
        logger.info("Searching for document with URL {}", url);
        Session session = sessionFactory.openSession(); // Open a new hibernate session
        Transaction transaction = null;
        SDADocument result = null;

        try {
            transaction = session.beginTransaction(); // Begin the transaction
            CriteriaBuilder criteriaBuilder = session.getCriteriaBuilder(); // Create a new CriteriaBuilder
            CriteriaQuery<SDADocument> criteriaQuery = criteriaBuilder.createQuery(SDADocument.class); // Create a new CriteriaQuery parameterized by the desired return type
            Root<SDADocument> sdaDocumentRoot = criteriaQuery.from(SDADocument.class); // Define the root entity
            criteriaQuery.where(criteriaBuilder.equal(sdaDocumentRoot.get("url"), url)); // Define the query
            result = session.createQuery(criteriaQuery).uniqueResult(); // Obtain the result of the query
            transaction.commit();
        } catch(Exception e) {
            if (transaction != null) {
                transaction.rollback();
                e.printStackTrace();
            }
        } finally {
            session.close(); // Close the session
        }
        return result; // Return the result
    }

    // Retrieve all of the SDADocument entities
    public List<SDADocument> findAllDocuments() {
        Session session = sessionFactory.openSession(); // Open a new Hibernate session
        Transaction transaction = null;
        List<SDADocument> result = null;

        try {
            transaction = session.beginTransaction(); // Begin the transactions
            CriteriaBuilder criteriaBuilder = session.getCriteriaBuilder(); // Create a new CriteriaBuilder
            //Create a new CriteriaQuery parameterized by the desired return type
            CriteriaQuery<SDADocument> criteriaQuery = criteriaBuilder.createQuery(
                    SDADocument.class
            );
            Root<SDADocument> sdaDocumentRoot = criteriaQuery.from(SDADocument.class); // Define the root entity
            CriteriaQuery<SDADocument> allDocuments = criteriaQuery.select(sdaDocumentRoot); // Define the query
            result = session.createQuery(allDocuments).getResultList(); // Obtain the result of the query
        } catch(Exception e) {
            if(transaction != null) {
                transaction.rollback();
                e.printStackTrace();
            }
        } finally {
            session.close(); // Close the session
        }
        return result; // Return the result
    }

    // Generic method to retrieve a list of entities related to the given SDADocument
    public <T> List<T> getDocumentRelation(SDADocument document, Class<T> relationClass) {
        Session session = sessionFactory.openSession(); // Open a new Hibernate session
        Transaction transaction = null;
        List<T> result = null;

        try {
            transaction = session.beginTransaction(); // Begin the transaction
            CriteriaBuilder criteriaBuilder = session.getCriteriaBuilder(); // Create a new CriteriaBuilder
            CriteriaQuery<T> criteriaQuery = criteriaBuilder.createQuery(relationClass); ////Create a new CriteriaQuery parameterized by the desired return type
            Root<T> root = criteriaQuery.from(relationClass); // Define the root entity
            // Define the query
            criteriaQuery.where(
                    criteriaBuilder.equal(
                            root.get("document"), document
                    )
            );
            result = session.createQuery(criteriaQuery).getResultList(); // Obtain the result of the query
        } catch(Exception e) {
            if(transaction != null) {
                transaction.rollback();
                e.printStackTrace();
            }
        } finally {
            session.close(); // Close the session
        }
        return result; // Return the result
    }
}
